x-trim in strings will result in joi trim(true) injection
acr-lfr/generate-it pull request #176
Opened 2024-01-16 12:02 UTC by j-d-carmichael

As the title says.

Working on a few new projects with existing code base I have found some mistakes relating to untrimmed input.

Or, in some cases, the trim input and then check string length.. if this else throw 422.

I would like to go further with this idea and modify it so as an string input automatically runs through `.trim(true)` and allow the yaml spec for the object to be able to opt out. There are much fewer use cases where as a dev you want the potential whitespace padding.

With this PR the following openapi spec:
```
type: object
required:
  - name
properties:
  name:
    type: string
    minLength: 1
    x-trim: true
```
Will result in the Joi validation looking like:

```
Joi.object({'name':Joi.string().trim(true).min(1).required()
```

Nice, but I would propose we opt in so all strings run through this, the change to this PR would mean the opt-out in the yml would look like:
```
type: object
required:
  - name
properties:
  name:
    type: string
    minLength: 1
    x-dont-trim: true
```

2024-01-16 12:21 UTC, acrontum-sanchez commented
Sounds good to me.
Wont "x-trim: false" be the same as "x-dont-trim: true" ?

2024-01-17 09:21 UTC, p-mcgowan commented on src/lib/helpers/SwaggerUtils.ts
> +        if (['opt-out', 'always'].includes(autoTrim)) {
this includes is not required since the check below covers all cases

2024-01-17 10:57 UTC, p-mcgowan approved these changes

2024-01-17 11:05 UTC, p-mcgowan requested changes
issues generating in a test project (discussion in another channel)

2024-01-19 08:47 UTC, p-mcgowan commented on .npmignore
> -src
src should be excluded from the node module

2024-01-19 08:49 UTC, p-mcgowan commented on .npmignore
> -src
alternatively you can simplify by adding files to package.json

```json
"files": [
    "README.md",
    "dist/"
]
```
Then only output files and the readme are included in the node_module

2024-01-20 09:25 UTC, p-mcgowan approved these changes

2024-01-20 14:22 UTC, merged